### ISSUE TITLE
How to run on local dev but connect to staging/production end point without building it?

### ISSUE THREAD

**Issue by kruyvanna** [stolenng/react-mobx-boilerplate#3]

**Comment by stolenng** [comment]
Change this(`index.tsx`):
![image](https://user-images.githubusercontent.com/17622381/185359364-ab06c8af-bdef-400b-a189-487cfe3f0934.png)
To:
![image](https://user-images.githubusercontent.com/17622381/185359549-4f57b399-0eed-41b7-9b7d-c32e5fd2abca.png)


And don't forget to move `env` folder to `public` le this:
![image](https://user-images.githubusercontent.com/17622381/185359655-588b1c67-d2c1-4d8e-ae80-da826da103e0.png)

Then you can just pass environment variable when running the project, also good for mocks..

**Comment by kruyvanna** [comment]
Thank you for your detailed reply.
But I just figured out that **process.env.NODE_ENV** always have **development** value.
but if I change variable name to **process.env.REACT_APP_ENV** it works.

So in package.json I can use sth like below
```
"start:production": "cross-env PORT=3006 REACT_APP_ENV=production react-scripts start",
```
